### ISSUE TITLE
Missing setup

### ISSUE THREAD

**Issue by janz93** [idealistic91/priceDataScraper#2]
It would be great if you could a detailed instruction of how I can setup the project.

example readme I created
* [multip_qa](https://bitbucket.org/janz93/multi_qa/src/00a7d390f3694e9c7943b24ff0473fa9815c3778/README.md?at=master&fileviewer=file-view-default)
* https://github.com/janz93/frequency-classes/blob/master/README.md

**Comment by idealistic91** [comment]
Thanks for the hint, I've updated the readme.md !
[readme.md](https://github.com/idealistic91/priceDataScraper/blob/master/README.md)

**Comment by janz93** [comment]
You are welcome.
To make the README a bit more readable I would suggest you to take a look at [markdown](https://guides.github.com/features/mastering-markdown/)
